version: "7"

services:
    appmovies:
      container_name: appmovies
      restart: always
      build: .
      links:
        - mongo
      ports:
        - "3000:3000"
      volumes:
        - .:/usr/src/app
    
    mongo:
      container_name: mongodatabase
      image: mongo
      ports:
          - "27017:27017"